# Generated by Django 2.0 on 2019-06-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190622_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
