# Generated by Django 2.0 on 2019-06-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_personmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonManager',
        ),
    ]
