# Generated by Django 2.0 on 2019-06-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
